services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=philoagents
      - MONGODB_INITDB_ROOT_PASSWORD=philoagents
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - philoagents-network
  api:
    profiles: ["python"]
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    networks:
      - philoagents-network
  java-api:
    profiles: ["java"]
    container_name: philoagents-java-api
    build:
      context: ./philoagents-java-api
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_HOST=local_pg
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_PORT=5432
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_DATABASE=philoagents-store
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_USERNAME=postgres
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_PASSWORD=postgres
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_DROPTABLEFIRST=true
      - PHILOAGENTS_LANGGRAPH_POSTGRESSAVER_CREATETABLES=true
    ports:
      - "8000:8000"
    networks:
      - philoagents-network
  local_pg:
    profiles: ["java"]  
    image: postgres:15
    container_name: local_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=philoagents-store
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - philoagents-network      
  ui:
    container_name: philoagents-ui
    build:
      context: ./philoagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./philoagents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - philoagents-network

volumes:
  data:
  config:

networks:
  philoagents-network:
    name: philoagents-network